#!/usr/bin/env bash
# =============================================================================
# launcher setup script — run once on a new machine
# Detects OS, installs dependencies, and creates a starter .env file.
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "═══════════════════════════════════════════════"
echo "  🚀 Project Launcher — Setup"
echo "═══════════════════════════════════════════════"
echo ""

# ── Detect OS ────────────────────────────────────────────────────────────────
OS="$(uname -s)"
case "$OS" in
  Linux*)  PLATFORM="linux" ;;
  Darwin*) PLATFORM="macos" ;;
  CYGWIN*|MINGW*|MSYS*) PLATFORM="windows" ;;
  *)       echo "⚠️  Unknown OS: $OS"; PLATFORM="unknown" ;;
esac
echo "  Detected platform: $PLATFORM"

# ── Check Node.js ────────────────────────────────────────────────────────────
if ! command -v node &>/dev/null; then
  echo "❌  Node.js is not installed."
  echo "   Install it from: https://nodejs.org/"
  exit 1
fi
NODE_VER=$(node --version)
echo "  Node.js $NODE_VER ✓"

if ! command -v npm &>/dev/null; then
  echo "❌  npm not found. Is Node.js installed correctly?"
  exit 1
fi

# ── Install dependencies ────────────────────────────────────────────────────
echo ""
echo "  Installing dependencies…"
npm install --production
echo "  ✓ Dependencies installed"

# ── Create .env file (optional, for machine-specific settings) ──────────────
ENV_FILE="$SCRIPT_DIR/.env"
if [ ! -f "$ENV_FILE" ]; then
  echo ""
  echo "  Creating starter .env file…"
  read -rp "  Enter your models directory path (e.g. ~/models): " MODELS_DIR
  # Expand ~ to home directory
  MODELS_DIR="${MODELS_DIR/#\~/$HOME}"
  read -rp "  Enter your Pithagoras directory path (e.g. ~/pithagoras): " PITH_DIR
  PITH_DIR="${PITH_DIR/#\~/$HOME}"
  read -rp "  Enter your Understory directory path (e.g. ~/understory): " UNDERSTORY_DIR
  UNDERSTORY_DIR="${UNDERSTORY_DIR/#\~/$HOME}"

  cat > "$ENV_FILE" <<EOF
# Project Launcher — Environment Configuration
# Generated by setup.sh on $(date +%Y-%m-%d)

# Optional: override the launcher's config storage directory
# (defaults to the launcher folder itself)
# LAUNCHER_DIR=

# Optional: override project directories
# PROJECT_DIR_PITHAGORAS=$PITH_DIR
# PROJECT_DIR_UNDERSTORY=$UNDERSTORY_DIR
# PROJECT_DIR_AGENTBOX=

# Optional: models directory (can also be set via the web UI)
MODELS_DIR=$MODELS_DIR

# Optional: terminal emulator for Pi Coding Agent
# (defaults: ptyxis → gnome-terminal → x-terminal-emulator)
# LAUNCHER_PI_TERMINAL=ptyxis
EOF
  echo "  ✓ Created $ENV_FILE"
  echo ""
  echo "  You can edit $ENV_FILE later to change these values."
else
  echo "  ℹ️  $ENV_FILE already exists — skipping."
fi

# ── Summary ──────────────────────────────────────────────────────────────────
echo ""
echo "═══════════════════════════════════════════════"
echo "  ✅ Setup complete!"
echo ""
echo "  Next steps:"
echo "    1. Edit .env to set your project directories"
echo "    2. Start the launcher:"
echo "       npm start"
echo "    3. Open: http://localhost:5000"
echo "═══════════════════════════════════════════════"
echo ""
