#Requires -Version 5.0
# =============================================================================
# launcher setup script — run once on a new machine (Windows)
# Detects OS, installs dependencies, and creates a starter .env file.
# =============================================================================

$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $ScriptDir

Write-Host "═══════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  🚀 Project Launcher — Setup (Windows)" -ForegroundColor Cyan
Write-Host "═══════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""

# ── Check Node.js ────────────────────────────────────────────────────────────
try {
    $nodeVer = node --version
    Write-Host "  Node.js $nodeVer ✓" -ForegroundColor Green
} catch {
    Write-Host "❌  Node.js is not installed." -ForegroundColor Red
    Write-Host "   Install it from: https://nodejs.org/" -ForegroundColor Yellow
    exit 1
}

if (-not (Get-Command npm -ErrorAction SilentlyContinue)) {
    Write-Host "❌  npm not found. Is Node.js installed correctly?" -ForegroundColor Red
    exit 1
}

# ── Install dependencies ────────────────────────────────────────────────────
Write-Host ""
Write-Host "  Installing dependencies…" -ForegroundColor Cyan
npm install --production
Write-Host "  ✓ Dependencies installed" -ForegroundColor Green

# ── Create .env file (optional, for machine-specific settings) ──────────────
$EnvFile = Join-Path $ScriptDir ".env"
if (-not (Test-Path $EnvFile)) {
    Write-Host ""
    Write-Host "  Creating starter .env file…" -ForegroundColor Cyan
    
    $home = [System.Environment]::GetEnvironmentVariable("USERPROFILE", "User")
    
    $modelsDir = Read-Host "  Enter your models directory path (e.g. C:\Users\$env:USERNAME\models)"
    $pithDir = Read-Host "  Enter your Pithagoras directory path (e.g. C:\Users\$env:USERNAME\pithagoras)"
    $understoryDir = Read-Host "  Enter your Understory directory path (e.g. C:\Users\$env:USERNAME\understory)"
    
    $envContent = @"
# Project Launcher — Environment Configuration
# Generated by setup.ps1 on $(Get-Date -Format "yyyy-MM-dd")

# Optional: override the launcher's config storage directory
# (defaults to the launcher folder itself)
# LAUNCHER_DIR=

# Optional: override project directories
# PROJECT_DIR_PITHAGORAS=$pithDir
# PROJECT_DIR_UNDERSTORY=$understoryDir
# PROJECT_DIR_AGENTBOX=

# Optional: models directory (can also be set via the web UI)
MODELS_DIR=$modelsDir

# Optional: terminal emulator for Pi Coding Agent
# (only relevant on Linux/macOS)
# LAUNCHER_PI_TERMINAL=ptyxis
"@
    
    Set-Content -Path $EnvFile -Value $envContent -Encoding UTF8
    Write-Host "  ✓ Created $EnvFile" -ForegroundColor Green
    Write-Host ""
    Write-Host "  You can edit $EnvFile later to change these values." -ForegroundColor Yellow
} else {
    Write-Host "  ℹ️  $EnvFile already exists — skipping." -ForegroundColor Gray
}

# ── Summary ──────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "═══════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  ✅ Setup complete!" -ForegroundColor Green
Write-Host ""
Write-Host "  Next steps:" -ForegroundColor Cyan
Write-Host "    1. Edit .env to set your project directories"
Write-Host "    2. Start the launcher:"
Write-Host "       npm start"
Write-Host "    3. Open: http://localhost:5000"
Write-Host "═══════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""
